services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi-app
    restart: unless-stopped
    depends_on:
      - mongo
    ports:
      - "8000:8000"
    env_file:
      - .env

  mongo:
    image: mongo
    container_name: fastapi-mongodb
    hostname: mongodb
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: